locations = ["france","germany","australia","brazil","england"]
print(f"'locations': {locations}")
print(f"list sorted with sorted(): {sorted(locations)}")
print(f"'locations': {locations}")
print(f"list sorted with sorted() in reverse order: {sorted(locations,reverse=True)}")   
print(f"'locations': _{locations}")
locations.reverse()
print(f"list sorted with .reverse(): {locations}")
locations.reverse()
print(f"list sorted with .reverse(): {locations}")
locations.sort()
print(f"list sorted with .sort(): {locations}")
locations.sort(reverse=True)
print(f"list sorted with .sort() in reverse order: {locations}")
print(f"The length of the list is: {len(locations)}")